version: '3.7'

services:

  r-market-front-end:
    image: react-ui

    volumes:
      - .:/react-ui
      - /react-ui/node_modules
    expose:
      - 5555
    ports:
      - "5555:5555"

    restart: unless-stopped
    environment:
      - CHOKIDAR_USEPOLLING=true
